### ISSUE TITLE
Vaadin 24 - button border radius style is not applied because of removed variable --lumo-border-radius

### ISSUE THREAD

**Issue by paodb** [vaadin-component-factory/vcf-pdf-viewer-flow#33]
When using the component in a Vaadin 24 application, the button border radius style is not applied as it depends on a l[umo variable that was removed](https://github.com/vaadin/web-components/commit/e347a7d4fedea4fb1f944cf35be3a8dc7ac41575).

Vaadin 24 button looks like: 

![pdf-toggle-button-v24](https://user-images.githubusercontent.com/30666649/224411045-eecb813b-9819-4220-8efd-1cd8e01b841c.png)

Should look as in previous versions:

![pdf-toggle-button-v23](https://user-images.githubusercontent.com/30666649/224411135-1d825823-6274-45ef-af8d-6b8ac98caf56.png)

**Comment by Frettman** [comment]
`--lumo-border-radius` was deprecated and the "new" name has been `--lumo-border-radius-m` for quite a while now. So no fallback necessary.

**Comment by javier-godoy** [comment]
The approach was chosen in order to preserve compatibility with Vaadin 22-24. Version 2.7 of this add-on is compatible with "Vaadin 22+", and so far this is the only issue when using the add-on with Vaadin 24. Replacing `--lumo-border-radius` with `--lumo-border-radius-m` is a breaking change, and it would require releasing (and maintaining) a new major version of the add-on just for a small CSS change.

With Vaadin 22-23, button `border-radius` styles are taken from `--lumo-border-radius`. When the add-on is used with Vaadin 24, `--lumo-border-radius` is undefined and `border-radius` styles then fallback to `--lumo-border-radius-s` (which has the same value as `--lumo-border-radius` in Vaadin 22-23).

https://github.com/vaadin-component-factory/vcf-pdf-viewer/blob/3241c181763fa34f8a22987bdf9753f13146495d/theme/lumo/vcf-pdf-viewer-styles.js#L75

**Comment by Frettman** [comment]
I'm pretty sure `--lumo-border-radius-m` already existed in Vaadin 22 (doc confirms it). But to be sure a fallback is fine of course. I mainly commented because I saw the commit and according to the docs `--lumo-border-radius-m` is the replacement for `--lumo-border-radius`.
Huh, but `--lumo-border-radius-s` seems to have the same value as `--lumo-border-radius-m`, so it visually makes no difference for now. Wierd. https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/shape

**Comment by paodb** [comment]
Thanks for pointing this out, I think you're right, the documentation recommends the use of `--lumo-border-radius-m` as replacement so I will update the fallback value.
